### PR TITLE
Numeric Patterns added

### PR DESCRIPTION
**Pull request by aakash232**
Fixes Issues #594 #600 #601 #602 #603 #689 #690 #691 #694 #695

### CODE REVIEW

**Comment by aakash232** [comment]
@aryashah2k 10 patterns added

**Review by tamalbag117 — CHANGES_REQUESTED** [review]
In the case of a public class, we can’t use a different file name.
Try to fix it. Or use default class .

**Review by aryashah2k — APPROVED** [review]

**Comment by aryashah2k** [comment]
@aakash232 , Please look into this and open a fresh PR, I have reverted this one

**Comment by aakash232** [comment]
Ok sir. Will change the public class name to file names respectively and open a fresh PR

**Pull request merged**
