### PR TITLE
Added patterns 17,18,20

### LINKED ISSUE #343: Code | Alphabetic Pattern 17

### LINKED ISSUE #344: Code | Alphabetic Pattern 18

### LINKED ISSUE #346: Code | Alphabetic Pattern 20

### LINKED ISSUE #571: Code | Numeric Pattern 54

### PR DESCRIPTION
**Pull request by Kajal13081**
Fixes #343 
Fixes #344 
Fixes #346
Fixes #571
#518 #519
#520 
#521 
#522 
#528
@aryashah2k @ChlorinePentoxide review this PR.

### CODE REVIEW

**Comment by aryashah2k** [comment]
@Kajal13081 , please go through the Discord SWOC channel for Patternhouse. The guidelines have been updated and minimum of 10 patterns are required in a PR to get the tag of Beginner(10 points). You can assign yourself some more patterns and update this PR with 10 patterns or more for it to be accepted by SWOC for its grading policy.

I strongly suggest you to check all the messages by me on our patternhouse channel ASAP

**Comment by Kajal13081** [comment]
> @Kajal13081 , please go through the Discord SWOC channel for Patternhouse. The guidelines have been updated and minimum of 10 patterns are required in a PR to get the tag of Beginner(10 points). You can assign yourself some more patterns and update this PR with 10 patterns or more for it to be accepted by SWOC for its grading policy.
> 
> I strongly suggest you to check all the messages by me on our patternhouse channel ASAP
Okay sure

**Comment by Kajal13081** [comment]
Okay sure

**Comment by aryashah2k** [comment]
Great, till then I will keep this PR open.

**Comment by aryashah2k** [comment]
4 more patterns to go for merging PR with beginner label(10 points). If you want issues assigned to you please mention me in those issues

**Comment by Kajal13081** [comment]
@aryashah2k Its done. Please review

**Review by aryashah2k — APPROVED** [review]

**Pull request merged**
