### PR TITLE
Alphabetic Pattern 66-68, 70, 132, 133, 166-191

### PR DESCRIPTION
**Pull request by Mahak008**

### CODE REVIEW

**Review by aryashah2k — APPROVED** [review]

**Comment by Mahak008** [comment]
@aryashah2k kindly do not merge this PR now.

**Comment by Mahak008** [comment]
Can you please open this PR for now.

**Comment by aryashah2k** [comment]
I've reverted the changes, just open a fresh PR with all the files again, that will remove the confusion. Only closed PRs can be reopened, merged PRs have to be reverted :)

**Comment by Mahak008** [comment]
> I've reverted the changes, just open a fresh PR with all the files again, that will remove the confusion. Only closed PRs can be reopened, merged PRs have to be reverted :)

Okay

**Comment by Mahak008** [comment]
Have you merged this PR ?

**Comment by aryashah2k** [comment]
Yes, even updated in the sheet. Will change the labels here just for record purpose.

**Pull request merged**
