### PR TITLE
Alphabetic Pattern in Java (97-100, 113, 114, 118-122, 134-139).

### PR DESCRIPTION
**Pull request by Mahak008**

### CODE REVIEW

**Review by aryashah2k — APPROVED** [review]

**Comment by Mahak008** [comment]
@aryashah2k Since their are 17 codes in this PR, if possible can the tag be changed to easy in place of beginner.

**Comment by aryashah2k** [comment]
I can change it in case you carry forward the three patterns in the next PR you open

**Comment by Mahak008** [comment]
> I can change it in case you carry forward the three patterns in the next PR you open

Okay. I will inform you when it will be done

**Comment by Mahak008** [comment]
> > I can change it in case you carry forward the three patterns in the next PR you open
> 
> Okay. I will inform you when it will be done

@aryashah2k There are 23 files in PR #893. So, can the 3 files be adjusted here now.

**Comment by aryashah2k** [comment]
Yes, I will update the tags and change in the sheet too

**Comment by Mahak008** [comment]
> Yes, I will update the tags and change in the sheet too

Thank You :)

**Pull request merged**
