### PR TITLE
Code for String Pattern (1-15) and Alphabetic Pattern (5-8, 31, 39, 72-96) in Java.

### PR DESCRIPTION
**Pull request by Mahak008**
Code for String Pattern in Java.

### CODE REVIEW

**Comment by aryashah2k** [comment]
Awesome, 4 more patterns to go to merge PR with Beginner tag @Mahak008

**Review by aryashah2k — COMMENTED** [review]
stringpattern14 is missing the .java extension. Please correct the same!

**Comment by Mahak008** [comment]
> stringpattern14 is missing the .java extension. Please correct the same!

I have uploaded it again with .java extension.

**Review by aryashah2k — APPROVED** [review]
Awesome work! Loved to review this PR. Keep up the good work!

**Comment by Mahak008** [comment]
> Awesome work! Loved to review this PR. Keep up the good work!

Thank you :)

**Pull request merged**
