### PR TITLE
added numericpattern247 to 254

### PR DESCRIPTION
**Pull request by Abhirv08**
solved issues #764 to #771

### CODE REVIEW

**Comment by Abhirv08** [comment]
@aryashah2k Also solved issue number #763

**Comment by aryashah2k** [comment]
1 pattern to go for the beginner tag @Abhirv08

**Comment by Abhirv08** [comment]
@aryashah2k  added numericpattern256. please review it

**Review by aryashah2k — APPROVED** [review]

**Comment by aryashah2k** [comment]
Please assign those issues before solving them It makes it hard for me to keep track of these things. Take precautions next time.

**Pull request merged**
